-- Master Init Schema
-- Generated: 2026-01-15 02:59:23

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- SEQUENCES
\i sequences/congress_trade_sessions_id_seq.sql
\i sequences/congress_trades_analysis_id_seq.sql
\i sequences/extracted_tickers_id_seq.sql
\i sequences/market_relationships_id_seq.sql
\i sequences/post_summaries_id_seq.sql
\i sequences/rss_feeds_id_seq.sql
\i sequences/sentiment_sessions_id_seq.sql
\i sequences/social_metrics_id_seq.sql
\i sequences/social_posts_id_seq.sql
\i sequences/social_sentiment_analysis_id_seq.sql

-- TABLES
\i tables/congress_trade_sessions.sql
\i tables/congress_trades_analysis.sql
\i tables/etf_holdings_log.sql
\i tables/extracted_tickers.sql
\i tables/market_relationships.sql
\i tables/post_summaries.sql
\i tables/research_articles.sql
\i tables/rss_feeds.sql
\i tables/securities.sql
\i tables/sentiment_sessions.sql
\i tables/social_metrics.sql
\i tables/social_posts.sql
\i tables/social_sentiment_analysis.sql

-- FUNCTIONS
\i functions/array_to_halfvec.sql
\i functions/array_to_sparsevec.sql
\i functions/array_to_vector.sql
\i functions/binary_quantize.sql
\i functions/cosine_distance.sql
\i functions/halfvec.sql
\i functions/halfvec_accum.sql
\i functions/halfvec_add.sql
\i functions/halfvec_avg.sql
\i functions/halfvec_cmp.sql
\i functions/halfvec_combine.sql
\i functions/halfvec_concat.sql
\i functions/halfvec_eq.sql
\i functions/halfvec_ge.sql
\i functions/halfvec_gt.sql
\i functions/halfvec_in.sql
\i functions/halfvec_l2_squared_distance.sql
\i functions/halfvec_le.sql
\i functions/halfvec_lt.sql
\i functions/halfvec_mul.sql
\i functions/halfvec_ne.sql
\i functions/halfvec_negative_inner_product.sql
\i functions/halfvec_out.sql
\i functions/halfvec_recv.sql
\i functions/halfvec_send.sql
\i functions/halfvec_spherical_distance.sql
\i functions/halfvec_sub.sql
\i functions/halfvec_to_float4.sql
\i functions/halfvec_to_sparsevec.sql
\i functions/halfvec_to_vector.sql
\i functions/halfvec_typmod_in.sql
\i functions/hamming_distance.sql
\i functions/hnsw_bit_support.sql
\i functions/hnsw_halfvec_support.sql
\i functions/hnsw_sparsevec_support.sql
\i functions/hnswhandler.sql
\i functions/inner_product.sql
\i functions/ivfflat_bit_support.sql
\i functions/ivfflat_halfvec_support.sql
\i functions/ivfflathandler.sql
\i functions/jaccard_distance.sql
\i functions/l1_distance.sql
\i functions/l2_distance.sql
\i functions/l2_norm.sql
\i functions/l2_normalize.sql
\i functions/sparsevec.sql
\i functions/sparsevec_cmp.sql
\i functions/sparsevec_eq.sql
\i functions/sparsevec_ge.sql
\i functions/sparsevec_gt.sql
\i functions/sparsevec_in.sql
\i functions/sparsevec_l2_squared_distance.sql
\i functions/sparsevec_le.sql
\i functions/sparsevec_lt.sql
\i functions/sparsevec_ne.sql
\i functions/sparsevec_negative_inner_product.sql
\i functions/sparsevec_out.sql
\i functions/sparsevec_recv.sql
\i functions/sparsevec_send.sql
\i functions/sparsevec_to_halfvec.sql
\i functions/sparsevec_to_vector.sql
\i functions/sparsevec_typmod_in.sql
\i functions/subvector.sql
\i functions/vector.sql
\i functions/vector_accum.sql
\i functions/vector_add.sql
\i functions/vector_avg.sql
\i functions/vector_cmp.sql
\i functions/vector_combine.sql
\i functions/vector_concat.sql
\i functions/vector_dims.sql
\i functions/vector_eq.sql
\i functions/vector_ge.sql
\i functions/vector_gt.sql
\i functions/vector_in.sql
\i functions/vector_l2_squared_distance.sql
\i functions/vector_le.sql
\i functions/vector_lt.sql
\i functions/vector_mul.sql
\i functions/vector_ne.sql
\i functions/vector_negative_inner_product.sql
\i functions/vector_norm.sql
\i functions/vector_out.sql
\i functions/vector_recv.sql
\i functions/vector_send.sql
\i functions/vector_spherical_distance.sql
\i functions/vector_sub.sql
\i functions/vector_to_float4.sql
\i functions/vector_to_halfvec.sql
\i functions/vector_to_sparsevec.sql
\i functions/vector_typmod_in.sql
