-- Signal Analysis Table
-- Stores technical signal analysis results for tickers
-- Migration: 39_signal_analysis.sql

CREATE TABLE IF NOT EXISTS signal_analysis (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(20) NOT NULL,
    analysis_date TIMESTAMP NOT NULL,
    structure_signal JSONB,
    timing_signal JSONB,
    fear_risk_signal JSONB,
    overall_signal VARCHAR(10),
    confidence_score FLOAT,
    explanation TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(ticker, analysis_date)
);

-- Index for fast lookups by ticker and date
CREATE INDEX IF NOT EXISTS idx_signal_analysis_ticker_date 
    ON signal_analysis(ticker, analysis_date DESC);

-- Index for filtering by overall signal
CREATE INDEX IF NOT EXISTS idx_signal_analysis_signal 
    ON signal_analysis(overall_signal);

-- Index for filtering by fear level (stored in fear_risk_signal JSONB)
CREATE INDEX IF NOT EXISTS idx_signal_analysis_fear_level 
    ON signal_analysis((fear_risk_signal->>'fear_level'));

-- RLS Policies
ALTER TABLE signal_analysis ENABLE ROW LEVEL SECURITY;

-- Policy: All authenticated users can read signal analysis
CREATE POLICY "Signal analysis is viewable by authenticated users"
    ON signal_analysis
    FOR SELECT
    TO authenticated
    USING (true);

-- Policy: Only admins can insert/update signal analysis
-- (Scheduler job will run as admin/service_role)
CREATE POLICY "Only admins can insert signal analysis"
    ON signal_analysis
    FOR INSERT
    TO authenticated
    WITH CHECK (is_admin(auth.uid()));

CREATE POLICY "Only admins can update signal analysis"
    ON signal_analysis
    FOR UPDATE
    TO authenticated
    USING (is_admin(auth.uid()));

-- Allow service role full access (for scheduler jobs)
CREATE POLICY "Service role can manage signal_analysis"
    ON signal_analysis
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Comments
COMMENT ON TABLE signal_analysis IS 'Technical signal analysis results for tickers. Generated by scheduled signal scan job.';
COMMENT ON COLUMN signal_analysis.ticker IS 'Ticker symbol (uppercase)';
COMMENT ON COLUMN signal_analysis.analysis_date IS 'Date/time of analysis (typically market close time)';
COMMENT ON COLUMN signal_analysis.structure_signal IS 'Structure signal data (trend, pullback, breakout) as JSONB';
COMMENT ON COLUMN signal_analysis.timing_signal IS 'Timing signal data (volume, RSI, CCI) as JSONB';
COMMENT ON COLUMN signal_analysis.fear_risk_signal IS 'Fear/risk signal data (volatility, drawdown, risk score) as JSONB';
COMMENT ON COLUMN signal_analysis.overall_signal IS 'Overall signal: BUY, SELL, HOLD, or WATCH';
COMMENT ON COLUMN signal_analysis.confidence_score IS 'Confidence score (0-1) for overall signal';
COMMENT ON COLUMN signal_analysis.explanation IS 'Optional AI-generated explanation of signals';
