-- Newsletter Inbox Schema Migration
-- Creates table for storing email newsletters with vector embeddings for semantic search
-- Uses pgvector extension for similarity search

-- Enable pgvector extension (if not already enabled)
CREATE EXTENSION IF NOT EXISTS vector;

-- Create newsletters table
CREATE TABLE IF NOT EXISTS newsletters (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Email metadata
    sender VARCHAR(500) NOT NULL,
    sender_name VARCHAR(500),
    recipient VARCHAR(500) NOT NULL,
    subject TEXT NOT NULL,
    
    -- Email content
    body_plain TEXT,
    body_html TEXT,
    
    -- Extracted/processed data
    tickers TEXT[], -- Array of ticker symbols mentioned
    summary TEXT, -- AI-generated summary (optional)
    
    -- Vector embedding for semantic search (768 dimensions for nomic-embed-text)
    embedding vector(768),
    
    -- Timestamps
    received_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP WITH TIME ZONE,
    
    -- Mailgun metadata
    message_id VARCHAR(500) UNIQUE, -- Mailgun message ID for deduplication
    
    -- Indexes
    CONSTRAINT newsletters_message_id_unique UNIQUE (message_id)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_newsletters_received_at ON newsletters(received_at DESC);
CREATE INDEX IF NOT EXISTS idx_newsletters_tickers ON newsletters USING GIN(tickers);
CREATE INDEX IF NOT EXISTS idx_newsletters_sender ON newsletters(sender);

-- Create vector similarity index using HNSW (Hierarchical Navigable Small World)
-- This enables fast approximate nearest neighbor search
CREATE INDEX IF NOT EXISTS idx_newsletters_embedding ON newsletters 
USING hnsw (embedding vector_cosine_ops);

-- Add comments for documentation
COMMENT ON TABLE newsletters IS 'Email newsletters received via Mailgun webhook with vector embeddings for semantic search';
COMMENT ON COLUMN newsletters.embedding IS 'Vector embedding (768-dim) generated by Ollama nomic-embed-text model for semantic similarity search';
COMMENT ON COLUMN newsletters.tickers IS 'Array of stock ticker symbols extracted from newsletter content';
COMMENT ON COLUMN newsletters.message_id IS 'Mailgun message ID for deduplication - prevents duplicate newsletters';
